# Generated by Django 5.0 on 2026-03-28 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_userprofile_age_userprofile_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='monthly_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='weekly_score',
            field=models.IntegerField(default=0),
        ),
    ]
